* doc/benefits.html: new.   * doc/index.html, doc/upgrade.html: adapt.   * etc/*/1, etc/*/3, etc/*/ctrlaltdel: set permissions on the magic files     instead of creating and removing them (can make them symbolic links     now); set PATH.   * runit.h: new; centralize runit's compiled in magic file names.   * runit.c: check permissions of magic files instead of sole existence;     conditionally call reboot(RB_AUTOBOOT), reboot(RB_POWER_OFF),     reboot(RB_HALT_SYSTEM) if possible; code cleanup.   * runit-init.c: set permissions on magic files instead of creating or     removing them; code cleanup.   * runsvdir.c: detect and tolerate system time warp; code cleanup.   * runsv.c, runsvchdir.c, runsvctrl.c, runsvstat.c, svwaitdown.c,     svwaitup.c, utmpset.c: code cleanup. 0.8.0.

diff --git a/etc/freebsd/1 b/etc/freebsd/1
--- a/etc/freebsd/1
+++ b/etc/freebsd/1
@@ -1,12 +1,17 @@
 #!/bin/sh
 # system one time tasks
+
+PATH=/command:/sbin:/bin:/usr/sbin:/usr/bin
 trap : 2
 trap : 3
 
-/bin/sh /etc/rc autoboot && exit 0
-
-# /etc/rc crashed, start emergency shell.
-echo '/etc/rc failed. Press <enter> for emergency shell...'
-read input
-/bin/sh -p
-/sbin/reboot
+sh /etc/rc autoboot
+if test $? -ne 0; then
+  # /etc/rc crashed, start emergency shell.
+  echo '/etc/rc failed. Press <enter> for emergency shell...'
+  read input
+  sh -p
+  exec reboot
+fi
+touch /etc/runit/stopit
+chmod 0 /etc/runit/stopit
